[package]
name = "resizr"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A Simple Image Resizer"
repository = "https://github.com/w3bdev1/resizr"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
image = "0.24.8"
